database:
 type: "mysql"
 server: "127.0.0.1"
 database: "BankAccount"
 username: "root"
 password: "123456"
 sqlitefile: "db.sqlite"

general:
  reloadAccountsMins: 30
 
interest:
 enabled: false
 default:
  percentage: 2.5
  ownerMustOnline: true
  minutes: 5

##DO NOT TOUCH ANYTHING BELOW THIS LINE!
version: 1