name: BankAccount
version: ${project.version}
authors: [TAT, autoit4you]
depend: [Vault]
main: de.autoit4you.bankaccount.BankAccount

commands:
 account:
    description: To interact with your accounts
    usage: /account help